name: Build

on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev vlc glibc-source libidn-dev libidn12 --fix-missing
          haxelib setup ~/haxelib
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install flxanimate --quiet
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
      - name: Compile
        run: haxelib run lime build linux
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: ./export/release/linux/bin
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install flxanimate --quiet
          haxelib install hxCodec --quiet
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
        shell: cmd
      - name: Compile
        run: haxelib run lime build windows
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: ./export/release/windows/bin
  buildMac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install flxanimate --quiet
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
      - name: Compile
        run: haxelib run lime build mac
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: ./export/release/macos/bin
  buildHTML:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install flxanimate --quiet
          haxelib install hxCodec --quiet
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved
      - name: Compile
        run: haxelib run lime build html5
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./export/release/html5/bin
